# Preface {.unnumbered}

This book was a long time coming. I had just finished a book Statistical Evidence in Medical Trials in 2006, and had a nice idea for a second book (this one that you are holding right now). It was more or less written, spread across a few dozen web pages that I had written over the past eight years. Surely, it would drop right into my lap.

Well, it was just like the John Lennon lyric in "Beautiful Boy" about how life is what happens while you're making other plans. Actually, that makes it sound like I had a bunch of unexpected (and maybe tragic) things happed over the past couple of decades. It is actually simpler than that. There's a computer term, thrashing, that refers to a multi-tasking computer that spends more time switching from task to task than in getting any of the tasks done. That's the verb that best describes my life. I'm thrashing.

Every year I'd show up at the Joint Statistics Meeting and look for the Cambridge University Press booth. I'd say hello, first to Lauren Cowles, and later to Arman Chowdhury. This is the year, I'd tell them, that I'll get the book written. I know exactly what I need to do. And every year, I'd write a lot less than I intended to. Too much thrashing.

I turned a corner (slowly) in 2023 when I converted my thin writings into a book project in Quarto. I really love Quarto and if you have been using RMarkdown for a while, you should really switch. It's an easy transition, and everything is so much more intuitive under Quarto.

So I'm finally done. It was a long time coming, but it's here. Read on!

Wait, it's not done yet. Here are the page counts for each chapter.

```{r}
#| message: false
#| warning: false
#| echo: false
#| label: page-counts

library(glue)
library(stringr)
library(tidyverse)

count_words <- function(fn) {
  read_lines(fn) |>
    paste0(collapse=" ") |>
    str_replace_all("[^a-z A-Z]", " ") |>
    str_replace_all(" +", "~") |> 
    str_split("~") |>
    unlist() |>
    length()
}

n <- count_words("index.qmd")

file_list <- list.files(path="chapters")
for (fn in file_list) {
  ni <- count_words(glue("chapters/{fn}"))
  n <- append(n, ni)
}
n_total <- sum(n)
paste0("-   Chapter ", 0:length(file_list), ": ", n) |>
  str_replace_all("Chapter 0", "Preface") |>
  str_replace_all("Chapter 22", "Summary") |>
  str_replace_all("Chapter 23", "Bibliography") |>
  paste0(collapse="\n") -> chapter_count
write_lines(c(n_total, n), paste0(Sys.Date(), ".txt"))
```

There are approximately `r n_total` words in the book. The word counts for individual chapters are

`r chapter_count`
